from ._sync import asyncify as asyncify
from ._proxy import LazyProxy as LazyProxy
from ._utils import (
    flatten as flatten,
    is_dict as is_dict,
    is_list as is_list,
    is_given as is_given,
    is_tuple as is_tuple,
    json_safe as json_safe,
    lru_cache as lru_cache,
    is_mapping as is_mapping,
    is_tuple_t as is_tuple_t,
    is_iterable as is_iterable,
    is_sequence as is_sequence,
    coerce_float as coerce_float,
    is_mapping_t as is_mapping_t,
    removeprefix as removeprefix,
    removesuffix as removesuffix,
    extract_files as extract_files,
    is_sequence_t as is_sequence_t,
    required_args as required_args,
    coerce_boolean as coerce_boolean,
    coerce_integer as coerce_integer,
    file_from_path as file_from_path,
    strip_not_given as strip_not_given,
    deepcopy_minimal as deepcopy_minimal,
    get_async_library as get_async_library,
    maybe_coerce_float as maybe_coerce_float,
    get_required_header as get_required_header,
    maybe_coerce_boolean as maybe_coerce_boolean,
    maybe_coerce_integer as maybe_coerce_integer,
    # New utility functions
    validate_api_key as validate_api_key,
    validate_client_credentials as validate_client_credentials,
    ResponseCache as ResponseCache,
    RateLimiter as RateLimiter,
    AdaptiveRateLimiter as AdaptiveRateLimiter,
    BatchProcessor as BatchProcessor,
    PaginationHelper as PaginationHelper,
    export_to_json as export_to_json,
    export_to_csv as export_to_csv,
    export_api_response as export_api_response,
    export_paginated_response as export_paginated_response,
    clear_response_cache as clear_response_cache,
    get_global_rate_limiter as get_global_rate_limiter,
    get_adaptive_rate_limiter as get_adaptive_rate_limiter,
    batch_process as batch_process,
    batch_process_async as batch_process_async,
    paginate as paginate,
    paginate_async as paginate_async,
    collect_all_pages as collect_all_pages,
    collect_all_pages_async as collect_all_pages_async,
    rate_limited as rate_limited,
    cached_response as cached_response,
    metrics_logger as metrics_logger,
    RequestMetrics as RequestMetrics,
    get_request_metrics as get_request_metrics,
    reset_request_metrics as reset_request_metrics,
)
from ._compat import (
    get_args as get_args,
    is_union as is_union,
    get_origin as get_origin,
    is_typeddict as is_typeddict,
    is_literal_type as is_literal_type,
)
from ._typing import (
    is_list_type as is_list_type,
    is_union_type as is_union_type,
    extract_type_arg as extract_type_arg,
    is_iterable_type as is_iterable_type,
    is_required_type as is_required_type,
    is_sequence_type as is_sequence_type,
    is_annotated_type as is_annotated_type,
    is_type_alias_type as is_type_alias_type,
    strip_annotated_type as strip_annotated_type,
    extract_type_var_from_base as extract_type_var_from_base,
)
from ._streams import consume_sync_iterator as consume_sync_iterator, consume_async_iterator as consume_async_iterator
from ._transform import (
    PropertyInfo as PropertyInfo,
    transform as transform,
    async_transform as async_transform,
    maybe_transform as maybe_transform,
    async_maybe_transform as async_maybe_transform,
)
from ._reflection import (
    function_has_argument as function_has_argument,
    assert_signatures_in_sync as assert_signatures_in_sync,
)
from ._datetime_parse import parse_date as parse_date, parse_datetime as parse_datetime
