# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing import List, Optional
from typing_extensions import Literal

from ..._models import BaseModel
from .completion_usage import CompletionUsage
from .chat_completion_token_logprob import ChatCompletionTokenLogprob

__all__ = [
    "CreateResponseStreamResponse",
    "Choice",
    "ChoiceDelta",
    "ChoiceDeltaToolCall",
    "ChoiceDeltaToolCallFunction",
    "ChoiceLogprobs",
]


class ChoiceDeltaToolCallFunction(BaseModel):
    """The function that the model called."""

    arguments: str
    """
    The arguments to call the function with, as generated by the model in JSON
    format. Note that the model does not always generate valid JSON, and may
    hallucinate parameters not defined by your function schema. Validate the
    arguments in your code before calling your function.
    """

    name: str
    """The name of the function to call."""


class ChoiceDeltaToolCall(BaseModel):
    id: str
    """The ID of the tool call."""

    function: ChoiceDeltaToolCallFunction
    """The function that the model called."""

    type: Literal["function"]
    """The type of the tool. Currently, only `function` is supported."""


class ChoiceDelta(BaseModel):
    """A chunk of the response message generated by the model."""

    content: Optional[str] = None
    """The contents of the chunk message.

    Can be null for chunks with tool calls or other non-text content.
    """

    reasoning_content: Optional[str] = None
    """The reasoning content generated by the model.

    Only present when the model generates reasoning text.
    """

    role: Optional[Literal["assistant"]] = None
    """The role of the message author. Only present in the first chunk."""

    tool_calls: Optional[List[ChoiceDeltaToolCall]] = None
    """The tool calls generated by the model, such as function calls.

    Only present when the model decides to call a tool.
    """


class ChoiceLogprobs(BaseModel):
    """Log probability information for the choice.

    Only present if logprobs was requested in the request.
    """

    content: Optional[List[ChatCompletionTokenLogprob]] = None
    """A list of message content tokens with log probability information."""


class Choice(BaseModel):
    delta: ChoiceDelta
    """A chunk of the response message generated by the model."""

    index: int
    """The index of the choice in the list of choices."""

    finish_reason: Optional[Literal["stop", "length", "tool_calls", "content_filter"]] = None
    """The reason the model stopped generating tokens.

    This will be `stop` if the model hit a natural stop point or a provided stop
    sequence, `length` if the maximum number of tokens specified in the request was
    reached, or `tool_calls` if the model called a tool. Only present in the final
    chunk.
    """

    logprobs: Optional[ChoiceLogprobs] = None
    """Log probability information for the choice.

    Only present if logprobs was requested in the request.
    """


class CreateResponseStreamResponse(BaseModel):
    """
    Represents a streamed chunk of a text-to-text response returned by the model, based on the provided input. VLLM models only.
    """

    id: str
    """A unique identifier for the response. Each chunk has the same ID."""

    choices: List[Choice]
    """A list of response choice chunks.

    Can contain more than one element if `n` is greater than 1. Can also be empty
    for the last chunk if you set `stream_options: {"include_usage": true}`.
    """

    created: int
    """The Unix timestamp (in seconds) of when the response was created.

    Each chunk has the same timestamp.
    """

    model: str
    """The model used to generate the response."""

    object: Literal["response.chunk"]
    """The object type, which is always `response.chunk`."""

    usage: Optional[CompletionUsage] = None
    """
    An optional field that will only be present when you set
    `stream_options: {"include_usage": true}` in your request. When present, it
    contains a null value **except for the last chunk** which contains the token
    usage statistics for the entire request. **NOTE:** If the stream is interrupted
    or cancelled, you may not receive the final usage chunk which contains the total
    token usage for the request.
    """
